# -*- coding: utf-8 -*-
"""Numberguessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkhJsWL5cwdLVy8W7l2bn3u1gzCRfDqf
"""

# Number Guessing Game

import random

secret_number = random.randint(1, 10)
attempt=3

while attempt>0:
 userguess=int(input("Enter the number:"))
 if(userguess>10):
  print("Invalid input range,Give input range between 1 to 10")
  continue
 elif(userguess>secret_number):
   print("your guess is too high,try again")
 elif(userguess<secret_number):
   print("your guess is too low,try again")
 elif(userguess==secret_number):
   print("wowiee!!!your guess is correct")
   break
   attempt -=1
else:
  print("Better luck next time")